language: node_js
node_js:
  - "4"
  - "6"
  - "8"
install:
  - npm install
script:
  - npm run lint
  - npm run test
bundler_args: --retry 2
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
after_script:
    - npm run coveralls
